### ISSUE TITLE
more of feature request than issue

### ISSUE THREAD

**Issue by Raytri3** [milo2012/nmap2nessus#2]
Would love to be able to select an existing policy, if possible. If I have already created a unique policy it would be cool if I could select that one instead of the creating the new one in the script. For example using the default "Basic Scan" that is delivered via Nessus.

**Comment by milo2012** [comment]
Hi Raytri3, thank you for this feature request, I have added the changes to the latest git push.
You can specify the policy name to use by using the -t argument.
