### ISSUE TITLE
Template option

### ISSUE THREAD

**Issue by git-oaktree** [milo2012/nmap2nessus#3]
Hello,

If I understand correctly, the -t option allows me to specify a templatefile (a policy) which will be used for the scan. What I have noticed is that the tool will correctly find the policy but it will then create a duplicate policy with a slightly modifiied name. For example if I used -t web_scan, I would a new policy named web_scan_01. 

Is there  a way to prevent nessus from creating the new policy? 

Thanks for creating the program

regards, 
Oaktree

**Comment by milo2012** [comment]
Please let me know if you still face any issues.
